services:
  mongodb:
    container_name: ${MONGODB_NAME}
    image: mongo:${MONGODB_IMAGE_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    restart: always
    volumes:
      - ${MONGODB_VOLUME_PATH}:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh admin --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
